
---

### **2. `docker-build/action.yaml`**

This is the **GitHub Action** YAML file for building the Docker image.

```yaml
name: 'Docker Build Action'
description: 'This action builds a Docker image for the Qublis project'

inputs:
  docker-image-name:
    description: 'The name of the Docker image to be built (e.g., qblis-node)'
    required: true
    default: 'qblis-node'

  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: false
    default: './Dockerfile'

runs:
  using: 'docker'
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.docker-image-name }} -f ${{ inputs.dockerfile-path }} .
    
    - name: Push Docker image
      run: |
        docker tag ${{ inputs.docker-image-name }} your-dockerhub-username/${{ inputs.docker-image-name }}:latest
        docker push your-dockerhub-username/${{ inputs.docker-image-name }}:latest
